language: python
script:
- python -m pytest
deploy:
  provider: heroku
  api_key:
    secure: n8S1R+mbyKVgKHkvr0eMw3KYxgzorFaj1JmvyKPFhmw2Ub7q3pm84ds96ReqOqRRwmIlxU6qE7yhKbO8iQ2p54WZ1N5o6wvZpZgx7II3TQOG6qrg93Z9GHs3oGiuwJmA8UfWvskzQqZahS7SE/2h9J/TZ7suuNIk+jvjGoZaWjMUuVnz78S2hAIA4547TpSlHCCEaMD+tgSFOEW8Y2FkcoBiDBEOVRIavnAhYi2+H2N28kPhDrL3p5jKU6yFQ4hQhteYDaqD39W61Zii65rcbqmdVyqtE/OnKmZQPCEMfbfH9htTKfoOXYhnOqY2KFoM8XryAZi8jIL3sSABaiDw3fmqQ5PGb+lfNEB0auE0A9ZSm8zSM8Qf3szwzf2CMc38iWa/F8i6M4y5ZTFKbvhhjXzAOCNYTfY24+5zz92viuh/y628KzqCExbty8QaFJZK5xHNQ4Yq/uSdkZp8Ebntvz9cuc9LrJcpU0ORxf0Y+9/CGBjq8F7C/X6POzqMd//xoRkeEWMU9rUsjkjJaC0Cc3+2ghnpjP8SD7MvygQlthGvICvkBd48adGzlyBP8+iP7U96fjv4S5d+kncbrS9sKYsine3PzBwvxTZ75s63Z/14jwafdkLnZ7c7TogUe+1aplNSl03cTiYZ5nOGDnOcPTX1a/Uk5BZELWrZTSG6Spc=
  app: boom-minesweeper
