language: python
script:
- python -m pytest
deploy:
  provider: heroku
  api_key:
    secure: Z7zZdgKWg73V1JBMDpOBq7P/4VdNxImdQ2lRL3ArxjOaW6hP8WR3rRSyc4RGN097lwaPv8GmV34jdKMFTTWNTuGkIeDX0/kATYaS28x0eZp4/mEeyzJQyXOupJY70+mwMAB/b5Ye0r06yTV1Ad3M7OOnFhIhDh41S2Wz13nhrWnSRmb9K0Xmx1LwpBao7gzf7zUzADlkDUnPs8WWDaQW4YkT8/7CBefOXBz+GQ1D0X851lNZIh+sq64klH0DMyBublaG55/SPhkGeTFVFnRA9hllLiogiwE1Ei7kskFhbYLmUaLN9aT0niZ4p8j1u5a//i2Ozr4Te1j75XR8zXVasQIdSTq/56UnS2SdjJN5qb+hpTJZw4fzDfLnlEe5NhXLG3NlaUPRs+sp22dIIVdGIcswL/L/muHbrVPs9jy+io5J8AC387BeLOwZVehKbHJstOnK7I/CgC5iFz2GpqNxpP3H7QQW+2py9j9PbXFs8PzlF2QSUBzsHB6vf1LdJRz80lCVH+SnLD358kthrhKwwFLZP7hlRgMPWOvzzJiWKghxhT9THuO+N0izw4EjtOerUAtG1AxqNlDaVT9yNLAZKiQetIsCSHFY1+0BFqV1uClffYxsNyh+oseufeVNmoW7d3MsXzEeKnX82sQHNDzEUu/iL9mvVuSNv5uEiwiqb+8=
  app: boom-minesweeper
